source 'https://rubygems.org'
#ruby=ruby-2.3.1
#ruby-gemset=Internships
ruby '2.3.1'

# -------- Web Server --------
gem 'puma'

# -------- Web Server --------
gem 'sinatra'
gem 'sinatra-contrib'

# ------ Hacking Pretty ------
gem 'slim'
gem 'sass'

# ---- Markdown Support ------
gem 'rdiscount'

group :development, :test do
  gem 'rake'
end

group :test do
  gem 'rubocop'
  gem 'rspec'
end
