source 'https://rubygems.org'
#ruby=ruby-2.3.1
#ruby-gemset=Internships
ruby '2.3.1'

# -------- Rack Server -------
gem 'puma'

# -------- Web Server --------
gem 'sinatra'
gem 'sinatra-contrib'
gem 'mongoid'

group :test do
  gem 'rubocop'
  gem 'rspec'
end
