begin
  require 'rspec/core/rake_task'

  task :test do
    RSpec::Core::RakeTask.new(:spec) do |t|
    t.pattern = 'spec/*_spec.rb'
    end
    Rake::Task["spec"].execute
  end
rescue LoadError
  # no rspec available
end
